### ISSUE TITLE
EDVP - Scheduling Jenkins Pipelines to run when there has been a new release using CRON.

### ISSUE THREAD

**Issue by santhosh-thangavel** [GSS-Cogs/family-edvp#31]
Implementation required to schedule each EDVP dataset pipeline to rerun on the latest publication.
Things to do:

- [x] Investigation on each pipeline needed to determine the latest and next release of each publication. (Can be found [here](https://docs.google.com/spreadsheets/d/1E2MbgtP0rE9rT-h7S55qDZ_YcbIF7LeaSmEJ2c-jBxY/edit#gid=159781742))

Implementation required on following pipelines/issues:

- [x] [BEIS-Digest-of-United-Kingdom-Energy-Statistics-DUKES-2020-annexes-E-to-J-and-long-term-trends-dataset](https://ci.floop.org.uk/job/GSS_data/job/EDVP/job/BEIS-Digest-of-United-Kingdom-Energy-Statistics-DUKES-2020-annexes-E-to-J-and-long-term-trends-dataset/) [#16](https://github.com/GSS-Cogs/family-edvp/issues/16)
Dataset on Hold

- [x] [BEIS-Digest-of-United-Kingdom-Energy-Statistics-DUKES-2020-main-chapters-and-annexes-A-to-D-dataset](https://ci.floop.org.uk/job/GSS_data/job/EDVP/job/BEIS-Digest-of-United-Kingdom-Energy-Statistics-DUKES-2020-main-chapters-and-annexes-A-to-D-dataset/) [#7](https://github.com/GSS-Cogs/family-edvp/issues/7)
Dataset on Hold

- [x] [BEIS-Energy-Trends-December-2020-special-feature-article-Electricity-generation-and-supply-in-Scotland-Wales-Northern-Ireland-and-England-2016-to-2019](https://ci.floop.org.uk/job/GSS_data/job/EDVP/job/BEIS-Energy-Trends-December-2020-special-feature-article-Electricity-generation-and-supply-in-Scotland-Wales-Northern-Ireland-and-England-2016-to-2019/) [#15](https://github.com/GSS-Cogs/family-edvp/issues/15)
Annual Publication.The next release not stated, however, an assumption has been made.
Would next run on Wednesday, December 22, 2021 10:01:47 AM GMT or via GitHub hook trigger

- [x] [BEIS-Final-UK-greenhouse-gas-emissions-national-statistics-1990-to-2019](https://ci.floop.org.uk/job/GSS_data/job/EDVP/job/BEIS-Final-UK-greenhouse-gas-emissions-national-statistics-1990-to-2019/) [#18](https://github.com/GSS-Cogs/family-edvp/issues/18)
Annual Publication.The next release not stated, however, an assumption has been made.
Would next run on Wednesday, February 2, 2022 10:01:00 AM GMT or via GitHub hook trigger

- [x] [BEIS-Fuel-poverty-detailed-tables-2020](https://ci.floop.org.uk/job/GSS_data/job/EDVP/job/BEIS-Fuel-poverty-detailed-tables-2020/) [#1](https://github.com/GSS-Cogs/family-edvp/issues/1)

- [x] [BEIS-Fuel-poverty-supplementary-tables-2020](https://ci.floop.org.uk/job/GSS_data/job/EDVP/job/BEIS-Fuel-poverty-supplementary-tables-2020/) [#5](https://github.com/GSS-Cogs/family-edvp/issues/5)

- [x] [BEIS-Fuel-used-in-generation-DUKES-5-3](https://ci.floop.org.uk/job/GSS_data/job/EDVP/job/BEIS-Fuel-used-in-generation-DUKES-5-3/) [#17](https://github.com/GSS-Cogs/family-edvp/issues/17)
Annual Publication.
Would next run on Thursday, July 29, 2021 10:01:24 AM BST or via GitHub hook trigger

- [x] [BEIS-Liquid-biofuels-for-transport-consumption-ET-6-2-quarterly](https://ci.floop.org.uk/job/GSS_data/job/EDVP/job/BEIS-Liquid-biofuels-for-transport-consumption-ET-6-2-quarterly/) [#8](https://github.com/GSS-Cogs/family-edvp/issues/8)
Quarterly Publication. The Pipeline is set to run in the month Sep, Dec, Mar and June.
Would next run on Thursday, September 30, 2021 11:31:38 AM BST or via GitHub hook trigger

- [x] [BEIS-Renewable-electricity-capacity-and-generation-ET-6-1-quarterly](https://ci.floop.org.uk/job/GSS_data/job/EDVP/job/BEIS-Renewable-electricity-capacity-and-generation-ET-6-1-quarterly/) [#10](https://github.com/GSS-Cogs/family-edvp/issues/10)
Quarterly Publication. The Pipeline is set to run in the month Sep, Dec, Mar and June.
Would next run on Thursday, September 30, 2021 10:31:21 AM BST or via GitHub hook trigger

- [x] [BEIS-Renewables-obligation-certificates-and-generation-monthly](https://ci.floop.org.uk/job/GSS_data/job/EDVP/job/BEIS-Renewables-obligation-certificates-and-generation-monthly/) [#13](https://github.com/GSS-Cogs/family-edvp/issues/13)
Monthly Publication. Would run between 8th-12th every month throughout the year.
Would next run on Thursday, July 8, 2021 10:31:28 AM BST or via GitHub hook trigger

- [x] [BEIS-RHI-monthly-deployment-data-Month-Year-Annual-edition](https://ci.floop.org.uk/job/GSS_data/job/EDVP/job/BEIS-RHI-monthly-deployment-data-Month-Year-Annual-edition/) [#12](https://github.com/GSS-Cogs/family-edvp/issues/12)
Monthly Publication. Would run between 17th-23rd every month throughout the year.
Would next run on Saturday, July 17, 2021 10:35:33 AM BST or via GitHub hook trigger

- [x] [BEIS-Sub-regional-Feed-in-Tariffs-confirmed-on-the-CFR-statistics](https://ci.floop.org.uk/job/GSS_data/job/EDVP/job/BEIS-Sub-regional-Feed-in-Tariffs-confirmed-on-the-CFR-statistics/) [#9](https://github.com/GSS-Cogs/family-edvp/issues/9)

- [x] [DfT-Electric-vehicle-charging-device-statistics-Month-Year-data-tables](https://ci.floop.org.uk/job/GSS_data/job/EDVP/job/DfT-Electric-vehicle-charging-device-statistics-Month-Year-data-tables/) [#11](https://github.com/GSS-Cogs/family-edvp/issues/11)
Annual Publication.
Would next run on Thursday, May 12th-13th day, 2022 10:01:22 AM BST or via GitHub hook trigger

- [x] [LCCC-Actual-ILR-Income](https://ci.floop.org.uk/job/GSS_data/job/EDVP/job/LCCC-Actual-ILR-Income/) [#14](https://github.com/GSS-Cogs/family-edvp/issues/14)

- [x] [Ofgem-Cheapest-tariffs-by-payment-method-Typical-domestic-dual-fuel-customer-GB](https://ci.floop.org.uk/job/GSS_data/job/EDVP/job/Ofgem-Cheapest-tariffs-by-payment-method-Typical-domestic-dual-fuel-customer-GB/) [#2](https://github.com/GSS-Cogs/family-edvp/issues/2)

- [x] [Ofgem-Retail-price-comparison-by-company-and-tariff-type-Domestic-GB](https://ci.floop.org.uk/job/GSS_data/job/EDVP/job/Ofgem-Retail-price-comparison-by-company-and-tariff-type-Domestic-GB/) [#3](https://github.com/GSS-Cogs/family-edvp/issues/3)

- [x] [Ofgem-Warm-Home-Discount-scheme](https://ci.floop.org.uk/job/GSS_data/job/EDVP/job/Ofgem-Warm-Home-Discount-scheme/) [#4](https://github.com/GSS-Cogs/family-edvp/issues/4)
